package com.example.composedemo.domain.model

object CurrencyInfo {

    val details = mapOf(
        "AED" to Pair("UAE Dirham", "🇦🇪"),
        "AFN" to Pair("Afghan Afghani", "🇦🇫"),
        "ALL" to Pair("Albanian Lek", "🇦🇱"),
        "AMD" to Pair("Armenian Dram", "🇦🇲"),
        "ANG" to Pair("Netherlands Antillean Guilder", "🇳🇱"),
        "AOA" to Pair("Angolan Kwanza", "🇦🇴"),
        "ARS" to Pair("Argentine Peso", "🇦🇷"),
        "AUD" to Pair("Australian Dollar", "🇦🇺"),
        "AWG" to Pair("Aruban Florin", "🇦🇼"),
        "AZN" to Pair("Azerbaijani Manat", "🇦🇿"),
        "BAM" to Pair("Bosnia-Herzegovina Convertible Mark", "🇧🇦"),
        "BBD" to Pair("Barbadian Dollar", "🇧🇧"),
        "BDT" to Pair("Bangladeshi Taka", "🇧🇩"),
        "BGN" to Pair("Bulgarian Lev", "🇧🇬"),
        "BHD" to Pair("Bahraini Dinar", "🇧🇭"),
        "BIF" to Pair("Burundian Franc", "🇧🇮"),
        "BMD" to Pair("Bermudan Dollar", "🇧🇲"),
        "BND" to Pair("Brunei Dollar", "🇧🇳"),
        "BOB" to Pair("Bolivian Boliviano", "🇧🇴"),
        "BRL" to Pair("Brazilian Real", "🇧🇷"),
        "BSD" to Pair("Bahamian Dollar", "🇧🇸"),
        "BTN" to Pair("Bhutanese Ngultrum", "🇧🇹"),
        "BWP" to Pair("Botswanan Pula", "🇧🇼"),
        "BYN" to Pair("Belarusian Ruble", "🇧🇾"),
        "BZD" to Pair("Belize Dollar", "🇧🇿"),
        "CAD" to Pair("Canadian Dollar", "🇨🇦"),
        "CDF" to Pair("Congolese Franc", "🇨🇩"),
        "CHF" to Pair("Swiss Franc", "🇨🇭"),
        "CLP" to Pair("Chilean Peso", "🇨🇱"),
        "CNY" to Pair("Chinese Yuan", "🇨🇳"),
        "COP" to Pair("Colombian Peso", "🇨🇴"),
        "CRC" to Pair("Costa Rican Colón", "🇨🇷"),
        "CUP" to Pair("Cuban Peso", "🇨🇺"),
        "CVE" to Pair("Cape Verdean Escudo", "🇨🇻"),
        "CZK" to Pair("Czech Koruna", "🇨🇿"),
        "DJF" to Pair("Djiboutian Franc", "🇩🇯"),
        "DKK" to Pair("Danish Krone", "🇩🇰"),
        "DOP" to Pair("Dominican Peso", "🇩🇴"),
        "DZD" to Pair("Algerian Dinar", "🇩🇿"),
        "EGP" to Pair("Egyptian Pound", "🇪🇬"),
        "ERN" to Pair("Eritrean Nakfa", "🇪🇷"),
        "ETB" to Pair("Ethiopian Birr", "🇪🇹"),
        "EUR" to Pair("Euro", "🇪🇺"),
        "FJD" to Pair("Fijian Dollar", "🇫🇯"),
        "FKP" to Pair("Falkland Islands Pound", "🇫🇰"),
        "GBP" to Pair("British Pound", "🇬🇧"),
        "GEL" to Pair("Georgian Lari", "🇬🇪"),
        "GHS" to Pair("Ghanaian Cedi", "🇬🇭"),
        "GIP" to Pair("Gibraltar Pound", "🇬🇮"),
        "GMD" to Pair("Gambian Dalasi", "🇬🇲"),
        "GNF" to Pair("Guinean Franc", "🇬🇳"),
        "GTQ" to Pair("Guatemalan Quetzal", "🇬🇹"),
        "GYD" to Pair("Guyanaese Dollar", "🇬🇾"),
        "HKD" to Pair("Hong Kong Dollar", "🇭🇰"),
        "HNL" to Pair("Honduran Lempira", "🇭🇳"),
        "HRK" to Pair("Croatian Kuna", "🇭🇷"),
        "HTG" to Pair("Haitian Gourde", "🇭🇹"),
        "HUF" to Pair("Hungarian Forint", "🇭🇺"),
        "IDR" to Pair("Indonesian Rupiah", "🇮🇩"),
        "ILS" to Pair("Israeli New Shekel", "🇮🇱"),
        "INR" to Pair("Indian Rupee", "🇮🇳"),
        "IQD" to Pair("Iraqi Dinar", "🇮🇶"),
        "IRR" to Pair("Iranian Rial", "🇮🇷"),
        "ISK" to Pair("Icelandic Króna", "🇮🇸"),
        "JMD" to Pair("Jamaican Dollar", "🇯🇲"),
        "JOD" to Pair("Jordanian Dinar", "🇯🇴"),
        "JPY" to Pair("Japanese Yen", "🇯🇵"),
        "KES" to Pair("Kenyan Shilling", "🇰🇪"),
        "KGS" to Pair("Kyrgystani Som", "🇰🇬"),
        "KHR" to Pair("Cambodian Riel", "🇰🇭"),
        "KMF" to Pair("Comorian Franc", "🇰🇲"),
        "KPW" to Pair("North Korean Won", "🇰🇵"),
        "KRW" to Pair("South Korean Won", "🇰🇷"),
        "KWD" to Pair("Kuwaiti Dinar", "🇰🇼"),
        "KYD" to Pair("Cayman Islands Dollar", "🇰🇾"),
        "KZT" to Pair("Kazakhstani Tenge", "🇰🇿"),
        "LAK" to Pair("Laotian Kip", "🇱🇦"),
        "LBP" to Pair("Lebanese Pound", "🇱🇧"),
        "LKR" to Pair("Sri Lankan Rupee", "🇱🇰"),
        "LRD" to Pair("Liberian Dollar", "🇱🇷"),
        "LSL" to Pair("Lesotho Loti", "🇱🇸"),
        "LYD" to Pair("Libyan Dinar", "🇱🇾"),
        "MAD" to Pair("Moroccan Dirham", "🇲🇦"),
        "MDL" to Pair("Moldovan Leu", "🇲🇩"),
        "MGA" to Pair("Malagasy Ariary", "🇲🇬"),
        "MKD" to Pair("Macedonian Denar", "🇲🇰"),
        "MMK" to Pair("Myanmar Kyat", "🇲🇲"),
        "MNT" to Pair("Mongolian Tugrik", "🇲🇳"),
        "MOP" to Pair("Macanese Pataca", "🇲🇴"),
        "MRU" to Pair("Mauritanian Ouguiya", "🇲🇷"),
        "MUR" to Pair("Mauritian Rupee", "🇲🇺"),
        "MVR" to Pair("Maldivian Rufiyaa", "🇲🇻"),
        "MWK" to Pair("Malawian Kwacha", "🇲🇼"),
        "MXN" to Pair("Mexican Peso", "🇲🇽"),
        "MYR" to Pair("Malaysian Ringgit", "🇲🇾"),
        "MZN" to Pair("Mozambican Metical", "🇲🇿"),
        "NAD" to Pair("Namibian Dollar", "🇳🇦"),
        "NGN" to Pair("Nigerian Naira", "🇳🇬"),
        "NIO" to Pair("Nicaraguan Córdoba", "🇳🇮"),
        "NOK" to Pair("Norwegian Krone", "🇳🇴"),
        "NPR" to Pair("Nepalese Rupee", "🇳🇵"),
        "NZD" to Pair("New Zealand Dollar", "🇳🇿"),
        "OMR" to Pair("Omani Rial", "🇴🇲"),
        "PAB" to Pair("Panamanian Balboa", "🇵🇦"),
        "PEN" to Pair("Peruvian Sol", "🇵🇪"),
        "PGK" to Pair("Papua New Guinean Kina", "🇵🇬"),
        "PHP" to Pair("Philippine Peso", "🇵🇭"),
        "PKR" to Pair("Pakistani Rupee", "🇵🇰"),
        "PLN" to Pair("Polish Zloty", "🇵🇱"),
        "PYG" to Pair("Paraguayan Guarani", "🇵🇾"),
        "QAR" to Pair("Qatari Rial", "🇶🇦"),
        "RON" to Pair("Romanian Leu", "🇷🇴"),
        "RSD" to Pair("Serbian Dinar", "🇷🇸"),
        "RUB" to Pair("Russian Ruble", "🇷🇺"),
        "RWF" to Pair("Rwandan Franc", "🇷🇼"),
        "SAR" to Pair("Saudi Riyal", "🇸🇦"),
        "SBD" to Pair("Solomon Islands Dollar", "🇸🇧"),
        "SCR" to Pair("Seychellois Rupee", "🇸🇨"),
        "SDG" to Pair("Sudanese Pound", "🇸🇩"),
        "SEK" to Pair("Swedish Krona", "🇸🇪"),
        "SGD" to Pair("Singapore Dollar", "🇸🇬"),
        "SHP" to Pair("Saint Helena Pound", "🇸🇭"),
        "SLL" to Pair("Sierra Leonean Leone", "🇸🇱"),
        "SOS" to Pair("Somali Shilling", "🇸🇴"),
        "SRD" to Pair("Surinamese Dollar", "🇸🇷"),
        "STN" to Pair("São Tomé and Príncipe Dobra", "🇸🇹"),
        "SVC" to Pair("Salvadoran Colón", "🇸🇻"),
        "SYP" to Pair("Syrian Pound", "🇸🇾"),
        "SZL" to Pair("Swazi Lilangeni", "🇸🇿"),
        "THB" to Pair("Thai Baht", "🇹🇭"),
        "TJS" to Pair("Tajikistani Somoni", "🇹🇯"),
        "TMT" to Pair("Turkmenistani Manat", "🇹🇲"),
        "TND" to Pair("Tunisian Dinar", "🇹🇳"),
        "TOP" to Pair("Tongan Paʻanga", "🇹🇴"),
        "TRY" to Pair("Turkish Lira", "🇹🇷"),
        "TTD" to Pair("Trinidad and Tobago Dollar", "🇹🇹"),
        "TVD" to Pair("Tuvaluan Dollar", "🇹🇻"),
        "TWD" to Pair("New Taiwan Dollar", "🇹🇼"),
        "TZS" to Pair("Tanzanian Shilling", "🇹🇿"),
        "UAH" to Pair("Ukrainian Hryvnia", "🇺🇦"),
        "UGX" to Pair("Ugandan Shilling", "🇺🇬"),
        "USD" to Pair("US Dollar", "🇺🇸"),
        "UYU" to Pair("Uruguayan Peso", "🇺🇾"),
        "UZS" to Pair("Uzbekistani Som", "🇺🇿"),
        "VES" to Pair("Venezuelan Bolívar", "🇻🇪"),
        "VND" to Pair("Vietnamese Dong", "🇻🇳"),
        "VUV" to Pair("Vanuatu Vatu", "🇻🇺"),
        "WST" to Pair("Samoan Tala", "🇼🇸"),
        "XAF" to Pair("Central African CFA Franc", "🌍"),
        "XCD" to Pair("East Caribbean Dollar", "🌎"),
        "XOF" to Pair("West African CFA Franc", "🌍"),
        "XPF" to Pair("CFP Franc", "🌏"),
        "YER" to Pair("Yemeni Rial", "🇾🇪"),
        "ZAR" to Pair("South African Rand", "🇿🇦"),
        "ZMW" to Pair("Zambian Kwacha", "🇿🇲"),
        "ZWL" to Pair("Zimbabwean Dollar", "🇿🇼")
    )

    fun getName(code: String): String = details[code]?.first ?: code

    fun getFlag(code: String): String = details[code]?.second ?: "🏳️"
}